## transforms needed for the camera mount in the flat config

# rotate around wrists z+ 45
Hwrist_rot45:
  [[0.7071,  -0.7071, 0, 0], # approx cos45, sin45
   [0.7071,  0.7071, 0, 0],
   [     0,         0, 1, 0],
   [     0,         0, 0, 1]]

# rot into to real sense frame (90 z+)
Hreal_rot:
  [[  0, -1, 0, 0], 
   [  1, 0, 0, 0],
   [  0, 0, 1, 0],
   [  0, 0, 0, 1]] # in m


# translate to real sense frame (still not aligned)
Hrot45_real:
  [[        1,   0,         0,  0],
   [        0,   1,         0, -0.03155],
   [        0,   0,         1, 0.098927],
   [        0,   0,         0, 1]] # in m


# dont tilt
Hreal_rot25:
  [[ 1, 0, 0, 0], 
   [ 0, 1, 0, 0],
   [ 0, 0, 1, 0],
   [ 0, 0, 0, 1]] # in m