## transforms needed for the camera mount in the flat config

# rotate around wrists z+ 45
Hwrist_rot45:
  [[0.7071,  -0.7071, 0, 0], # approx cos45, sin45
   [0.7071,  0.7071, 0, 0],
   [     0,         0, 1, 0],
   [     0,         0, 0, 1]]


# translate to real sense frame (still not aligned)
Hrot45_real:
  [[        1,   0,         0,  0.03155],
   [        0,   1,         0,        0],
   [        0,   0,         1, 0.098927],
   [        0,   0,         0,        1]] # in m


# align with camera link
Hreal_roty:
  [[  0,  0, 1, 0], 
   [  0, -1, 0, 0],
   [  1,  0, 0, 0],
   [  0,  0, 0, 1]] # in m

# include translation to camera link
Hreal_rot2cam:
  [[ 1, 0, 0, 0.0106], 
   [ 0, 1, 0, 0.0175],
   [ 0, 0, 1, 0.0125],
   [ 0, 0, 0,      1]] # in m