## transforms needed for the camera mount tiled to 25 deg


# rotate around wrists z+ 45
Hwrist_rot45:
  [[0.7071, -0.7071,   0, 0], # approx cos45, sin45
   [0.7071,  0.7071,   0, 0],
   [     0,       0,   1, 0],
   [     0,       0,   0, 1]]

# rot into to real sense frame (90 z+)
Hreal_rot90:
  [[  0, -1, 0, 0], 
   [  1, 0, 0, 0],
   [  0, 0, 1, 0],
   [  0, 0, 0, 1]] # in m

# translate to real sense frame
Hrot45_real:
  [[        1,   0,          0, 0],
   [        0,   1,          0, -0.054785],
   [        0,   0,          1, 0.105262],
   [        0,   0,          0, 1]] # in m

# tilt down by 25 (-x)
Hrot90_rot25:
  [[ 1,         0, 0      ,  0], # approx cos25, sin25
   [ 0,  0.906307, 0.422618, 0],
   [ 0, -0.422618, 0.906307, 0],
   [ 0,         0, 0       , 1]] # in m